In [8]:
import pandas as pd
import numpy as np

2023-11-27 01:43:12,973 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.

In [9]:
employees_data = pd.read_excel(r'C:\Users\Blouz\Desktop\S9\Projet SST\Updated_Employees_Data.xlsx')

In [10]:
tasks_data = pd.read_excel(r'C:\Users\Blouz\Desktop\S9\Projet SST\New_Tasks_Data.xlsx')

## rule-based algorithm.

In [18]:
# Creating a predictive model to recommend an employee for a given task

# Function to predict the most suitable employee for a given task
def predict_employee_for_task(task_required_skill, task_day, task_shift, employees_data):
    # Finding employees who have the required skill
    skilled_employees = employees_data[employees_data['Skills'].apply(lambda skills: task_required_skill in skills)]

    # Filter employees who are available on the required day and shift
    available_employees = skilled_employees[
        (skilled_employees['Available_Days'].apply(lambda days: task_day in days)) &
        (skilled_employees['Available_Shifts'].apply(lambda shifts: task_shift in shifts))
    ]

    # If no employees are available, return a message indicating this
    if available_employees.empty:
        return "No suitable employee found"

    # TODO: Further criteria for selecting the best employee can be added here
    # For now, we select the first suitable employee
    selected_employee = available_employees.iloc[0]['Employee_ID']

    return selected_employee

# Example prediction
# Task requires 'Assembly' skill, scheduled for day 4 (Thursday), and during the 1st shift
predicted_employee = predict_employee_for_task('Assembly', 4, 1, employees_data)
predicted_employee

'E_002'

## Hungarian Algorithm

In [24]:
import pandas as pd
import numpy as np
from scipy.optimize import linear_sum_assignment


# Creating a cost matrix for the Hungarian Algorithm
# For demonstration, using a random cost matrix
num_employees = len(employees_data)
num_tasks = len(tasks_data)
cost_matrix = np.random.rand(num_tasks, num_employees)

# Applying the Hungarian algorithm
row_ind, col_ind = linear_sum_assignment(cost_matrix)

# Create a DataFrame to display the task to employee assignments
assignments_df = pd.DataFrame({
    'Task_ID': tasks_data['Task_ID'].iloc[row_ind].values,
    'Assigned_Employee_ID': employees_data['Employee_ID'].iloc[col_ind].values
})

assignments_df

   Task_ID Assigned_Employee_ID
0    T_001                E_017
1    T_002                E_006
2    T_003                E_020
3    T_004                E_009
4    T_005                E_041
5    T_006                E_019
6    T_007                E_010
7    T_008                E_039
8    T_009                E_038
9    T_010                E_046
10   T_011                E_018
11   T_012                E_022
12   T_013                E_036
13   T_014                E_001
14   T_015                E_027
15   T_016                E_040
16   T_017                E_055
17   T_018                E_025
18   T_019                E_024
19   T_020                E_029
20   T_021                E_002
21   T_022                E_012
22   T_023                E_013
23   T_024                E_011
24   T_025                E_048
25   T_026                E_051
26   T_027                E_021
27   T_028                E_056
28   T_029                E_045
29   T_030                E_026